version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      # Install dependencies needed
      - npm install
      - echo Installing NPM..

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
      - echo Installing awscli..
  pre_build:
    commands:
      # Build the react app to give an optimized production build
      - npm run build
  build:
    commands:
      # Copy the content of build folder into website s3 bucket
      - aws s3 sync build/ s3://$WEBSITE_S3_BUCKET/
